### ISSUE TITLE
Gibbs Free energy Calculation

### ISSUE THREAD

**Issue by shahid-sattar** [ftherrien/VaspGibbs#1]
First of all, thanks for making this codes available.
Please excuse me but I am trying to learn how to calculate Gibbs Free energy in a reaction. Assuming a reaction for two-dimensional case of TMDCs , 
MoSe2 (solid) + 2Te(gas) ---> MoTe2 (solid)+ 2Se (gas)

I can calculate the energies of terms, e.g., single-layer MoSe2 (solid) and MoTe2 (solid). Perhaps for Te and Se energies of a single atom is a box but all these values are at 0K and does not include Temperature (T) effects.

It is therefore I am wondering how can I use VaspGibbs code to study this reaction?
It would be extremely useful to have some insight.
Thanks,

**Comment by shahid-sattar** [comment]
After a successful installation, I tried to run the code on top of a finished scf cycle for a 2D system, it gives the following error:

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Traceback (most recent call last):
  File "/home/s/sattars/anaconda3/bin/vasp_gibbs", line 139, in <module>
    main()
  File "/home/s/sattars/anaconda3/bin/vasp_gibbs", line 118, in main
    I_mat = get_inertia(cell, atoms, get_masses(atoms))
  File "/home/s/sattars/anaconda3/lib/python3.8/site-packages/vaspgibbs/thermo.py", line 109, in get_masses
    masses[i] = mass_elem[elements==a[0]][0]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1

**Comment by ftherrien** [comment]
@shahid-sattar I think I found the problem. Let me know if it works for you now with v0.1.1

**Comment by shahid-sattar** [comment]
So, should I need to reinstall the repository and try again?

**Comment by shahid-sattar** [comment]
Hi, thanks for the effort. 
I tried again, but it didn't work.
In fact, for a single S atom in a big cell, I ran frequency calculation (IBRION=5, NSW=100, NFREE=2) and later used vaspkit on that, which gives me the following result (image 1). However, when I try to run vasp_gibbs on top of scf or frequency calculation for the same S atom, it doesn't run and ends with error.
First screenshot is for vaspkit and second, third is for vasp_gibbs on top of scf, frequency calculation for S atom in a big cell.
<img width="1260" alt="Screenshot 2022-05-08 at 22 36 14" src="https://user-images.githubusercontent.com/61748682/167315101-4e62fdb3-229b-444a-a5fc-4956b20f3f18.png">
<img width="1260" alt="Screenshot 2022-05-08 at 22 46 37" src="https://user-images.githubusercontent.com/61748682/167315225-bb69693e-ba7f-4e06-8a09-bb602ae2e0a8.png">
<img width="1359" alt="Screenshot 2022-05-08 at 22 48 06" src="https://user-images.githubusercontent.com/61748682/167315280-2496d0c2-48db-47b5-9c7b-7d3277804419.png">

**Comment by shahid-sattar** [comment]
It would be great if you kindly post an example, let's say for the reaction 
2D MoS2 (solid) + 2 Se (gas) ----> 2D MoSe2 (solid) + 2 S (gas)
using vasp_gibbs that can clarify the whole procedure step by step with analysis of energies.
It would be a great great help.

**Comment by ftherrien** [comment]
Hi @shahid-sattar, vasp gibbs was not handling single atoms well, let me know if the new version (v0.1.2) works for you. 

As for your question about the reaction and how to use VaspGibbs, I moved it to the [discussion section](https://github.com/ftherrien/VaspGibbs/discussions/2#discussion-4062409).

**Comment by shahid-sattar** [comment]
Hi, thanks again for your very generous time and effort.
1 clarification, should I run vasp_Gibbs on top of scf run or frequency run? 
I’ll check this now. 
thanks

**Comment by ftherrien** [comment]
@shahid-sattar if you run it on top of an scf run it will run the frequency calculation for you, if you run it on top of a frequency run, it will use your results from that calculation. So both should work.

**Comment by shahid-sattar** [comment]
Alright. Apparently, it now worked.
1. For a supercell (2x2x2), first I did a frequency run (IBRION=8)
2. Then I ran vasp_gibbs on top of above calculation as it seems that vasp_gibbs requires frequencies in the OUTCAR and somehow re-calculates them.
But running vasp_gibbs at a specified T and P after this calculation write VaspGibbs.md file which contains the required information.
As this is done for a 2x2x2 supercell, I think there needs some division to get values for / unitcell.  Below is the output which it write after this run. Still trying to understand the parameters on the output run. Perhaps some brief description would be very helpful, especially which values of energies should be used in reaction.

<img width="1243" alt="Screenshot 2022-05-12 at 22 21 03" src="https://user-images.githubusercontent.com/61748682/168161951-eac6a13c-d0ba-48da-b2bc-480a621ce41d.png">

**Comment by ftherrien** [comment]
@shahid-sattar glad it worked! I will add IBRION = 7 and 8 to the acceptable IBRION parameters for frequency calculations. You don't need to run your own frequency calculations before you run `vasp_gibbs`, it will run them for you. If you wish, you can specify which IBRION to use with the `--ibrion` flag. To see all the available flags you can do `vasp_gibbs --help`.

What you want to use for your calculations is the value next to "Gibbs Free Energy". Let me know in the discussions section if you have more specific questions about the output. BTW I encourage you to open VaspGibbs.md in a Markdown language interpreter like [dillinger.io](dillinger.io), it will look nicer!!

Can I mark this issue as resolved?

**Comment by shahid-sattar** [comment]
Thanks again. On last part, how to cite the package?

**Comment by ftherrien** [comment]
There is no publication attached to it for now. You can simply link this repo so that other people know where to find it!

**Comment by ftherrien** [comment]
@shahid-sattar it's been almost a year, but I have now added a citation section in the README
